import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import { useEffect } from "react";
import { db } from "./_app";
import {
  getDoc,
  deleteDoc,
  doc,
  setDoc,
  getDocs,
  collection,
} from "firebase/firestore";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  useEffect(() => {
    console.log("WOELD");
  }, []);

  const handleCreate = async () => {
    try {
      // const res = await addDoc(collection(db, "users"), {
      //   first: "CHO",
      //   middle: "YUNSIK",
      //   born: 961209,
      // });
      const project = doc(db, "portfolio", "portfolio");
      const res = await setDoc(
        project,
        { name: "포트폴리오", regDt: "2024.01.30", contents: "성공했습니다." },
        { merge: true },
      );
      console.log(res);
    } catch (e) {
      console.log(e);
    }
  };

  const handleRead = async () => {
    try {
      const project = doc(db, "portfolio", "allreborn");
      const res = await getDoc(project);
      const res2 = await getDocs(collection(db, "portfolio"));
      console.log(res.data());
      console.log(res2.docs);
    } catch (e) {
      console.log(e);
    }
  };

  const handleDelete = async () => {
    try {
      const project = doc(db, "portfolio", "portfolio");
      const res = await deleteDoc(project);
      console.log(res);
    } catch (e) {
      console.log(e);
    }
  };

  // 컬렉션조회 (목록조회) getDocs(collection(db, collectionName))
  // 문서조회 (상세조회) getDoc(doc(db, collectionName, docsName))

  // 컬렉션&문서생성 addDoc(doc(db, collectionName), {fieldData})

  // 문서수정 updateDoc(doc(db, collectionName, docsName), {fieldData})

  // 문서삭제 deleteDoc(doc(db, collectionName, docsName))

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main} ${inter.className}`}>
        <div className={styles.description}>
          <p>
            Get started by editing&nbsp;
            <code className={styles.code}>src/pages/index.tsx</code>
            <button type="button" onClick={handleCreate}>
              PUSH USER
            </button>
            <button type="button" onClick={handleRead}>
              GET USER
            </button>
            <button type="button" onClick={handleDelete}>
              DELETE USER
            </button>
          </p>
          <div>
            <a
              href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
              target="_blank"
              rel="noopener noreferrer"
            >
              By{" "}
              <Image
                src="/vercel.svg"
                alt="Vercel Logo"
                className={styles.vercelLogo}
                width={100}
                height={24}
                priority
              />
            </a>
          </div>
        </div>

        <div className={styles.center}>
          <Image
            className={styles.logo}
            src="/next.svg"
            alt="Next.js Logo"
            width={180}
            height={37}
            priority
          />
        </div>

        <div className={styles.grid}>
          <a
            href="https://nextjs.org/docs?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}
            target="_blank"
            rel="noopener noreferrer"
          >
            <h2>
              Docs <span>-&gt;</span>
            </h2>
            <p>
              Find in-depth information about Next.js features and&nbsp;API.
            </p>
          </a>

          <a
            href="https://nextjs.org/learn?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}
            target="_blank"
            rel="noopener noreferrer"
          >
            <h2>
              Learn <span>-&gt;</span>
            </h2>
            <p>
              Learn about Next.js in an interactive course with&nbsp;quizzes!
            </p>
          </a>

          <a
            href="https://vercel.com/templates?framework=next.js&utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}
            target="_blank"
            rel="noopener noreferrer"
          >
            <h2>
              Templates <span>-&gt;</span>
            </h2>
            <p>
              Discover and deploy boilerplate example Next.js&nbsp;projects.
            </p>
          </a>

          <a
            href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}
            target="_blank"
            rel="noopener noreferrer"
          >
            <h2>
              Deploy <span>-&gt;</span>
            </h2>
            <p>
              Instantly deploy your Next.js site to a shareable URL
              with&nbsp;Vercel.
            </p>
          </a>
        </div>
      </main>
    </>
  );
}
